### PR TITLE
#2999 introduced a new pattern checker and implemented a new function…

### PR DESCRIPTION
**Pull request by Vijay-Chaudhary**
… within PHPMailer. This enhancement enables you to directly invoke getLastTransactionID on PHPMailer itself

### CODE REVIEW

**Comment by Synchro** [comment]
I don't think this is a good idea as it opens the door to calling it erroneously on an instance that's not using SMTP.

I've not heard of VcMailer – could you show an example SMTP transaction log that shows its style of output? Also, I would not expect a 2.0.0 response to a successful DATA command.

**Comment by Vijay-Chaudhary** [comment]
1. The getLastTransactionID function has been removed from PHPMailer.

2. **VcMailer** is a dummy name containing my first and last name's ( Vijay Chaudhary )  first character and Mailer so it looks like **VcMailer**.

3. Here is the real response I am getting from PHPMailer
**Note: I have changed my email and the password is the response** 

D:\php7.3\htdocs\leetcode\githubContribution\sendmail.php:52:
object(PHPMailer\PHPMailer\PHPMailer)[3]
  public 'Priority' => null
  public 'CharSet' => string 'UTF-8' (length=5)
  public 'ContentType' => string 'text/html' (length=9)
  public 'Encoding' => string '7bit' (length=4)
  public 'ErrorInfo' => string '' (length=0)
  public 'From' => string 'example@gmail.com' (length=22)
  public 'FromName' => string 'Vijay Chaudhary' (length=11)
  public 'Sender' => string '' (length=0)
  public 'Subject' => string 'XYZ & Contracting Company -' (length=27)
  public 'Body' => string 'Hello, This is a test mail.' (length=27)
  public 'AltBody' => string '' (length=0)
  public 'Ical' => string '' (length=0)
  protected 'MIMEBody' => string 'Hello, This is a test mail.
' (length=29)
  protected 'MIMEHeader' => string 'Date: Mon, 8 Jan 2024 17:48:45 +0100
To: example@gmail.com
From: Vijay Chaudhary <example@gmail.com>
Subject: XYZ & Contracting Company -
Message-ID: <DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0@localhost>
X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
' (length=344)
  protected 'mailHeader' => string '' (length=0)
  public 'WordWrap' => int 0
  public 'Mailer' => string 'smtp' (length=4)
  public 'Sendmail' => string '/usr/sbin/sendmail' (length=18)
  public 'UseSendmailOptions' => boolean true
  public 'ConfirmReadingTo' => string '' (length=0)
  public 'Hostname' => string '' (length=0)
  public 'MessageID' => string '' (length=0)
  public 'MessageDate' => string '' (length=0)
  public 'Host' => string 'smtp.gmail.com' (length=14)
  public 'Port' => int 25
  public 'Helo' => string '' (length=0)
  public 'SMTPSecure' => string 'tls' (length=3)
  public 'SMTPAutoTLS' => boolean true
  public 'SMTPAuth' => boolean true
  public 'SMTPOptions' => 
    array (size=0)
      empty
  public 'Username' => string 'example@gmail.com' (length=22)
  public 'Password' => string 'password' (length=19)
  public 'AuthType' => string '' (length=0)
  protected 'SMTPXClient' => 
    array (size=0)
      empty
  protected 'oauth' => null
  public 'Timeout' => int 300
  public 'dsn' => string '' (length=0)
  public 'SMTPDebug' => int 0
  public 'Debugoutput' => string 'html' (length=4)
  public 'SMTPKeepAlive' => boolean false
  public 'SingleTo' => boolean false
  protected 'SingleToArray' => 
    array (size=0)
      empty
  public 'do_verp' => boolean false
  public 'AllowEmpty' => boolean false
  public 'DKIM_selector' => string '' (length=0)
  public 'DKIM_identity' => string '' (length=0)
  public 'DKIM_passphrase' => string '' (length=0)
  public 'DKIM_domain' => string '' (length=0)
  public 'DKIM_copyHeaderFields' => boolean true
  public 'DKIM_extraHeaders' => 
    array (size=0)
      empty
  public 'DKIM_private' => string '' (length=0)
  public 'DKIM_private_string' => string '' (length=0)
  public 'action_function' => string '' (length=0)
  public 'XMailer' => string '' (length=0)
  protected 'smtp' => 
    object(PHPMailer\PHPMailer\SMTP)[2]
      public 'do_debug' => int 0
      public 'Debugoutput' => string 'html' (length=4)
      public 'do_verp' => boolean false
      public 'Timeout' => int 300
      public 'Timelimit' => int 300
      protected 'smtp_transaction_id_patterns' => 
        array (size=12)
          'exim' => string '/[\d]{3} OK id=(.*)/' (length=20)
          'sendmail' => string '/[\d]{3} 2.0.0 (.*) Message/' (length=28)
          'postfix' => string '/[\d]{3} 2.0.0 Ok: queued as (.*)/' (length=34)
          'Microsoft_ESMTP' => string '/[0-9]{3} 2.[\d].0 (.*)@(?:.*) Queued mail for delivery/' (length=56)
          'Amazon_SES' => string '/[\d]{3} Ok (.*)/' (length=17)
          'SendGrid' => string '/[\d]{3} Ok: queued as (.*)/' (length=28)
          'CampaignMonitor' => string '/[\d]{3} 2.0.0 OK:([a-zA-Z\d]{48})/' (length=35)
          'Haraka' => string '/[\d]{3} Message Queued \((.*)\)/' (length=33)
          'ZoneMTA' => string '/[\d]{3} Message queued as (.*)/' (length=32)
          'Mailjet' => string '/[\d]{3} OK queued as (.*)/' (length=27)
          'MailerSend' => string '/[\d]{3} Message queued as (.*)/' (length=32)
          'VjMailer' => string '/[\d]{3} 2.0.0 OK (.*)/' (length=23)
      protected 'last_smtp_transaction_id' => string '1704732530 l6-20020a170902d34600b001d4ea483473sm125301plk.82 - gsmtp' (length=68)
      protected 'smtp_conn' => null
      protected 'error' => 
        array (size=4)
          'error' => string '' (length=0)
          'detail' => string '' (length=0)
          'smtp_code' => string '' (length=0)
          'smtp_code_ex' => string '' (length=0)
      protected 'helo_rply' => null
      protected 'server_caps' => null
      protected 'last_reply' => string '221 2.0.0 closing connection l6-20020a170902d34600b001d4ea483473sm125301plk.82 - gsmtp
' (length=88)
  protected 'to' => 
    array (size=1)
      0 => 
        array (size=2)
          0 => string 'example@gmail.com' (length=22)
          1 => string '' (length=0)
  protected 'cc' => 
    array (size=0)
      empty
  protected 'bcc' => 
    array (size=0)
      empty
  protected 'ReplyTo' => 
    array (size=0)
      empty
  protected 'all_recipients' => 
    array (size=1)
      'example@gmail.com' => boolean true
  protected 'RecipientsQueue' => 
    array (size=0)
      empty
  protected 'ReplyToQueue' => 
    array (size=0)
      empty
  protected 'attachment' => 
    array (size=0)
      empty
  protected 'CustomHeader' => 
    array (size=0)
      empty
  protected 'lastMessageID' => string '<DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0@localhost>' (length=55)
  protected 'message_type' => string 'plain' (length=5)
  protected 'boundary' => 
    array (size=3)
      1 => string 'b1=_DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0' (length=47)
      2 => string 'b2=_DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0' (length=47)
      3 => string 'b3=_DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0' (length=47)
  protected 'language' => 
    array (size=0)
      empty
  protected 'error_count' => int 0
  protected 'sign_cert_file' => string '' (length=0)
  protected 'sign_key_file' => string '' (length=0)
  protected 'sign_extracerts_file' => string '' (length=0)
  protected 'sign_key_pass' => string '' (length=0)
  protected 'exceptions' => boolean true
  protected 'uniqueid' => string 'DMVPQ1JmbIA3ypxQHPEPUV8r1sxWbygTEWaywcHNmW0' (length=43)
  public 'SMTP_PORT' => string '587' (length=3)

**Message sent! last_smtp_transaction_id:1704732530 l6-20020a170902d34600b001d4ea483473sm125301plk.82 - gsmtp**

**Comment by Synchro** [comment]
I was looking for the *SMTP response*, not a dump of your instance. Set `SMTPDebug = 2` and show what it says after the end of the DATA command, which should be something like:

    2024-01-08 17:12:16	CLIENT -> SERVER: .
    2024-01-08 17:12:16	SERVER -> CLIENT: 250 Ok: queued as 12345

Overall though, there is no point in adding your personal proprietary mail server's response in the base library – if you need to recognise your own service, make a child class and override the method to add the pattern.

**Comment by Vijay-Chaudhary** [comment]
Here is the response of SMTP 
```
2024-01-09 16:35:58 CLIENT -> SERVER: Hello, This is a test mail.
2024-01-09 16:35:58 CLIENT -> SERVER:
2024-01-09 16:35:58 CLIENT -> SERVER: .
2024-01-09 16:35:59 SERVER -> CLIENT: 250 2.0.0 OK 1704818159 30-20020a630c5e000000b005cd835182c5sm1827492pgm.79 - gsmtp
2024-01-09 16:35:59 CLIENT -> SERVER: QUIT
2024-01-09 16:35:59 SERVER -> CLIENT: 221 2.0.0 closing connection 30-20020a630c5e000000b005cd835182c5sm1827492pgm.79 - gsmtp
```

Whatever you want to call it instead of **VcMailer** you can or you can suggest a name or you can make your pattern key. I will be happy in all ways. **This is my first contribution to open-source** so I am not sure about making a child class and overwriting the existing functionality

**Comment by Synchro** [comment]
That example looks like gmail, and gmail's IDs are opaque in that they don't represent anything to anyone outside of Google. For all the other patterns, you can the ID they provide to trace what happened to a message. The reason they are all different shapes is that there is no standard for this – it's not part of the SMTP spec, so all these implementations have made something up.

You don't have to make changes to the base class to change how it behaves. For example, to add your own pattern, you could do this in a child class:

```php
class mySMTP extends SMTP
{
protected $smtp_transaction_id_patterns = [
        'exim' => '/[\d]{3} OK id=(.*)/',
        'sendmail' => '/[\d]{3} 2.0.0 (.*) Message/',
        'postfix' => '/[\d]{3} 2.0.0 Ok: queued as (.*)/',
        'Microsoft_ESMTP' => '/[0-9]{3} 2.[\d].0 (.*)@(?:.*) Queued mail for delivery/',
        'Amazon_SES' => '/[\d]{3} Ok (.*)/',
        'SendGrid' => '/[\d]{3} Ok: queued as (.*)/',
        'CampaignMonitor' => '/[\d]{3} 2.0.0 OK:([a-zA-Z\d]{48})/',
        'Haraka' => '/[\d]{3} Message Queued \((.*)\)/',
        'ZoneMTA' => '/[\d]{3} Message queued as (.*)/',
        'Mailjet' => '/[\d]{3} OK queued as (.*)/',
        'VcMailer' => '/[\d]{3} 2.0.0 OK (.d+).* - gsmtp/',
    ];
}
```
Then pass it to your PHPMailer instance to replace the default SMTP class:

```php
$mail = new PHPMailer;
$mail->setSMTPInstance(new mySMTP);
```

**Pull request closed without merging**
