### PR TITLE
visibility required

### PR DESCRIPTION
**Pull request by MathiasReker**
Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.

### CODE REVIEW

**Comment by Synchro** [comment]
Judging by your string of PRs, you seem unaware that this has to run on PHP 5.5.

**Comment by MathiasReker** [comment]
I am sorry about that. I have overlooked this.

**Comment by Synchro** [comment]
The CI runs will show you where the problems are, should you want to persevere, but this will unfortunately apply to a lot of your PRs!

**Comment by MathiasReker** [comment]
> Judging by your string of PRs, you seem unaware that this has to run on PHP 5.5.

Yes, you are right! I overlooked this.

**Pull request closed without merging**
