### PR TITLE
updated misleading comment on sample for smtp/google via xoauth2 #890

### PR DESCRIPTION
**Pull request by muratyaman**
also added gitignore line for intellij idea project folder

### CODE REVIEW

**Comment by Synchro** [comment]
Don't put `.idea` in there. It's platform-specific and belongs in your global `.gitignore` config, not in every project, much like `.DS_store` files should be ignored. Could you take that out and force-push please.

**Comment by muratyaman** [comment]
Sure

**Comment by muratyaman** [comment]
ok?

**Comment by Synchro** [comment]
Perfect, thanks.

I can see you've got quite a bit of activity history, but Github says this was your first PR. Congrats, if so!

**Comment by muratyaman** [comment]
No problem. I'm not used to PRs, I created a few PRs before :)
but I mainly worked on private repos on github and bitbucket before.

**Pull request merged**
