### PR TITLE
6.0 Docblock update

### PR DESCRIPTION
**Pull request by andela-iadeniyi**

### CODE REVIEW

**Comment by Synchro** [comment]
Could you rebase on latest 6.0 and force-push this please?

**Comment by Synchro** [comment]
I forgot to say "and squash all into one commit" please!

**Comment by andela-iadeniyi** [comment]
Okay, I will make the update.

**Comment by Synchro** [comment]
I don't think you did that right. When it all works, this PR will be condensed into a single commit based on the current HEAD. Short guide here: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by Synchro** [comment]
Thanks, glad you got that figured out! I have a suspicion that phpcs and phpcbf have some bugs in - most of the issues like these were flagged, but for some reason these ones were not.

**Pull request merged**
