### PR TITLE
XOAuth Provider - Google,Yahoo,Microsoft

### PR DESCRIPTION
**Pull request by hayageek**
I have added XOAuth Provider support for Google(existing),Yahoo,Microsoft

### CODE REVIEW

**Comment by Synchro** [comment]
Don't add those dependencies as `requires` - put them in `suggests` as otherwise it will break BC with anyone running PHP < 5.4.

**Comment by hayageek** [comment]
OK. I will make the backward comparability for additional oauthProviderName property, by defaulting it to Google.
Let me fix all the errors and I will provide the clean code.

**Comment by Synchro** [comment]
No, I'm saying that if you put each provider in its own class, you don't need the provider name at all - it's implicit in the class name.

**Comment by hayageek** [comment]
But how the PHPMailerOAuth knows to pick the right provider class name. 
If you don't mind can you explain bit .

**Comment by hayageek** [comment]
got it 
For example: .
1).PHPMailOauthGoogle  extends PHPMailerOAuth 
$mail = new PHPMailOauthGoogle();
2).PHPMailOauthYahoo  extends PHPMailerOAuth 
$mail = new PHPMailOauthYahoo();

is that OK ?

**Comment by Synchro** [comment]
Yes, that way the individual provider classes will be very simple.

**Comment by hayageek** [comment]
Please review the code.

**Comment by hayageek** [comment]
Fixed all the issues.

**Comment by hayageek** [comment]
Please let me know the changes are ok

**Comment by Synchro** [comment]
I've accepted this into the xoauth branch, I need to change some things before merging into master.

**Comment by hayageek** [comment]
Thanks. Slowly I will add some more providers.
Yandex, Mail.ru

**Comment by Synchro** [comment]
Cool. The main change I want to make is that the `phpmaileroauthprovider` base class should not inherit from the `phpmaileroauth` class. There's no reason for the providers to be PHPMailer child classes - PHPMailer needs to *use* them, but not *be* them. It may be that I need to introduce other child classes to make that work, I've not thought through how best to arrange it yet.

**Pull request closed without merging**
