### PR TITLE
DSN suppot added

### PR DESCRIPTION
**Pull request by carlosmaug**
Hi

I made some changes to have support for DSN notification requests. I hope this could be included in the main branch.

Regards

### CODE REVIEW

**Comment by Synchro** [comment]
That's good - could you add some unit tests (look in the tests folder) for coverage and to show it working? Also add a link to [RFC3461](https://tools.ietf.org/html/rfc3461) in the phpdocs for the `$dsn` property.

**Comment by carlosmaug** [comment]
As you suggested I added some unit tests to cover the code and show it is working. I also added the link to RFC3461 in the phpdocs.

**Comment by carlosmaug** [comment]
Done, I think now all is correct.

**Comment by Synchro** [comment]
Thanks.

**Pull request merged**
