### PR TITLE
Solving problems sending mail using SMTP

### PR DESCRIPTION
**Pull request by JoseCage**
In order to solve Bug #525 and #149 using phpmailer lib, changed the line 16 in the file located in PHPMailer/examples/gmail.phps, corresponding to the SMTP server configuration pasting $mail->Ismail(); instead of $mail->isSMTP(); and it worked perfectly in my testing, both on localhost as in remote server.

 failures already discussed in issues #525 and #149.

  With this hope I can help other programmers have passed the problem.

### CODE REVIEW

**Comment by Synchro** [comment]
I'm sorry but this is an utterly clueless change. You're suggesting "fixing" SMTP by not using SMTP. It's not an appropriate solution to either of the bugs linked, and why would you alter a "how to use SMTP" example so that it does not use SMTP?

**Comment by JoseCage** [comment]
Hello @Synchro, I understand you and you are quite right. I have reviewed my code and tested it again and confirmed that she was wearing the wrong way. Since using Ismail(); literally not the SMTP credentials necessary. With this I learned once more from my mistakes. So I hope suggestions. Thank you very much. :+1:

**Comment by Synchro** [comment]
It's not really that - if you want to use SMTP and it's broken, fix whatever is wrong with you mail server or network - it's not a PHPMailer problem. Switching to `isMail` usually isn't an appropriate solution - it's like suggesting that the way to fix your broken-down car is to walk instead.

**Comment by JoseCage** [comment]
Got it. Thank you once again for the explanation and excuse for failure.

  In case you need to delete this pull request in order to avoid possible mistakes (:bug:) by other developers, accepted without problems.

**Comment by FalsAlarm** [comment]
I'm trying to use phpmailer with gmail for smtp mail settings. however doesn't matter what settings i try, still get GMail SMTP connect() failed

**Comment by FalsAlarm** [comment]
Does anyone know how to fix that error?

**Comment by FalsAlarm** [comment]
below is my code for the phpmailer and gmail smtp settings.

[code]
	public function SendEmailToUser($email, $subject, $message, $plainTextMessage)
	{
		//require_once './includes/mailer/class.phpmailer.php';
		
		/**
		 * This example shows settings to use when sending via Google's Gmail servers.
		 */
		//SMTP needs accurate times, and the PHP time zone MUST be set
		//This should be done in your php.ini, but this is how to do it if you don't have access to that
		date_default_timezone_set('Etc/UTC');
		//require '../PHPMailerAutoload.php';
		require_once("./includes/mailer/PHPMailerAutoload.php");
		//Create a new PHPMailer instance
		$mail = new PHPMailer;
		//Tell PHPMailer to use SMTP
		$mail->isSMTP();
		//Enable SMTP debugging
		// 0 = off (for production use)
		// 1 = client messages
		// 2 = client and server messages
		$mail->SMTPDebug = 2;
		//Ask for HTML-friendly debug output
		$mail->Debugoutput = 'html';
		//Set the hostname of the mail server
		$mail->Host = 'smtp.gmail.com';
		// use
		// $mail->Host = gethostbyname('smtp.gmail.com');
		// if your network does not support SMTP over IPv6
		//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
		$mail->Port = 587;
		$mail->isHTML = false;
		//Set the encryption system to use - ssl (deprecated) or tls
		//$mail->SMTPSecure = 'tls';
		$mail->SMTPSecure = 'tls';
		//Whether to use SMTP authentication
		$mail->SMTPAuth = true;
		//Username to use for SMTP authentication - use full email address for gmail
		$mail->Username = "******@gmail.com";
		//Password to use for SMTP authentication
		$mail->Password = "********";
		//Set who the message is to be sent from
		$mail->setFrom('canadeals@gmail.com', 'Ricky Mossip');
		//Set an alternative reply-to address
		$mail->addReplyTo('canadeals@sasktel.net', 'Ricky Mossip');
		//Set who the message is to be sent to
		$mail->addAddress($email, 'First Nation Circle Member');
		//Set the subject line
		$mail->Subject = $subject;
		//Read an HTML message body from an external file, convert referenced images to embedded,
		//convert HTML into a basic plain-text alternative body
		$mail->msgHTML($message);
		//Replace the plain text body with one created manually
		$mail->AltBody = $message;
		//Attach an image file
		//$mail->addAttachment('images/phpmailer_mini.png');
		//send the message, check for errors
		if (!$mail->send()) {
			echo "<p>Mailer Error: " . $mail->ErrorInfo . "</p>";
		} else {
			echo "<h2>Message sent!</h2>";
		}
	}
[/code]

**Comment by FalsAlarm** [comment]
by the way, the default code in gmail.phps file also produces this same error.

**Comment by Synchro** [comment]
Don't hijack old, closed issues for unrelated requests. Read the docs that the error message points you at.

**Pull request closed without merging**
