### PR TITLE
add parameter SMTPSecure to example smtp.phps

### PR DESCRIPTION
**Pull request by yantze**
No parameter SMTPSecure cause 
```
SMTP connect() failed
```

### CODE REVIEW

**Comment by Synchro** [comment]
Sorry, no. Setting ssl with port 25 is pretty much guaranteed to fail, and undermines this being a minimal SMTP example.

**Comment by yantze** [comment]
Smtp also can use port 576 and 587

I use the port 576, if not add SMTPSecure to ssl, it will run fail, so do i push another example ?

**Comment by yantze** [comment]
Also can indicate port 576 use ssl and port 587 use tls

**Comment by Synchro** [comment]
No. There are plenty of other examples that demonstrate `SMTPSecure`, and PHPMailer will work with explicit TLS automatically anyway. SSL on port 465 has been deprecated since 1998, so we do not want to encourage it. There is no need to change this basic example to be compatible with your non-standard setup.

**Comment by yantze** [comment]
Deprecated but developers must use it, because many(at least my country) mail providers only provide service ssl with 465

This is not changed by developers, and this problem took me a lot of time. may be others also.

So i suggest that add another example such as smtp_legacy_netease_sina.phps file.

It may be more convenient for developers.

**Comment by Synchro** [comment]
It's not worth adding a whole new example that's only 5 bytes different, especially when it's already covered extensively in documentation.

**Pull request closed without merging**
