### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by apple-fan-pl**
...

### CODE REVIEW

**Comment by Synchro** [comment]
None of this is actual refactoring - there are only whitespace and comment changes.

**Comment by apple-fan-pl** [comment]
@Synchro if its not code refactoring, than whats this?

**Comment by Synchro** [comment]
Just messing with whitespace - there are no actual code changes in any of what you did.

**Comment by apple-fan-pl** [comment]
> Just messing with whitespace - there are no actual code changes in any of what you did.

yes butit still is refactoring....

**Comment by Synchro** [comment]
It might be if the changes actually improved clarity or consistency, but they're not even doing that. If you're looking for something useful to do (which would be much appreciated), look at increasing test coverage.

**Comment by apple-fan-pl** [comment]
@Synchro All right, but why not to merge this PR? Whats wrong with it?

**Comment by Synchro** [comment]
Because it adds nothing of value. I'm not interested in accepting PRs that make changes for the sake of change.

**Pull request closed without merging**
