### PR TITLE
Composer: update version constraints for PHPUnit Polyfills

### PR DESCRIPTION
**Pull request by jrfnl**
PHPUnit Polyfills 1.0.0 has been released.

Ref: https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.0

### CODE REVIEW

**Comment by remicollet** [comment]
Probably better to keep `^0.2.0 || ^1.0.0`

No reason to bump dependency, until new feature of 1.0.0 are really used.

**Comment by jrfnl** [comment]
Well, it's a dev dependency, so there's no chance of the constraints conflicting with those of projects using this library, which is why I didn't really think that would be necessary.

**Review by jesus-khristian — APPROVED** [review]

**Comment by Synchro** [comment]
This needs a tweak to deal with the conflict with the change in #2364

**Comment by Synchro** [comment]
Which I've now done...

**Pull request merged**
