### PR TITLE
Add travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by manish364824**
Hi,
I had added ppc64le(Linux on Power) support on travis-ci in the branch and looks like its been successfully added. I believe it is ready for the final review and merge. The travis ci build logs can be verified from the link below.

https://travis-ci.com/github/manish364824/PHPMailer/builds/199599627

Please have a look.

Regards,
Manish

### CODE REVIEW

**Comment by Synchro** [comment]
I'm hesitant to merge this for two reasons.
1. Does anyone use the Power arch any more? I've not really heard anything about it since early 2000s. I'm not exactly overrun with requests for it...
2. I'm quite keen to move away from Travis to Github actions, and more complexity on Travis will make that harder, and I'm not sure if GH supports Power anyway.

**Comment by manish364824** [comment]
@gerrith3
Could you please look into this?

**Comment by gerrith3** [comment]
@Synchro Power is definitely not dead - two of the top3 in the top500 supercomputers, running major workloads throughout banking worldwide, wall street and trading programs, high end retail world wide, etc.  Most of the customers are Global 500 users and most have a high level of confidentiality in their workloads, hence you won't see them generally interacting in open source software, except for a few key clients.  There are also other vendors now manufacturing Power hardware with a focus more on desktop and medium scale servers.  IBM Cloud has hundreds of 200+ core servers running Power, with more cores, more systems coming.  It is hard to track who might be using an individual project, but your package is part of debian/ubuntu ppc64le distributions today and probably others.
GHA does not support Power today - we are working on a runner model and a way to get free access to hardware.  No ETA on that yet.  You could also do a hybrid model of GHA for Intel and Travis for Power/arm/MacOS/etc if you needed.

**Comment by Synchro** [comment]
I have merged master back into this branch as there have bene substantial changes in the Travis config for PHP 8, and I wanted to be sure your changes would work with the new config before merging.

**Comment by Synchro** [comment]
Sorry to drop you in it, but I couldn't resist a PR to migrate everything to GitHub actions, so I'm afraid that your Power build isn't happening any more. If you can get a runner set up, I'd be happy to merge that in again.

**Comment by gerrith3** [comment]
@Synchro c'est la via, je suppose...  We are working to set up a runner but the boot strapping of .NET is a PITA for Power and the golang runner is pretty limited (probably works if you have your own hardware, but not part of any cloud environment for now).

**Pull request merged**
