### PR TITLE
php://temp streams instead of temp files

### PR DESCRIPTION
**Pull request by Gratusfr**
@TODO would be nice to use php://temp streams here > done

### CODE REVIEW

**Comment by Synchro** [comment]
Thanks for taking the initiative!. Could you fix [the coding standards failures highlighted in Travis](
https://travis-ci.org/PHPMailer/PHPMailer/jobs/447200109) please.

**Comment by Gratusfr** [comment]
What are the standards failures to fix ? Mayby spaces before "$body = $parts[1];" ?

**Comment by Gratusfr** [comment]
Seem working when I PR but seem brocken now.

**Comment by Synchro** [comment]
Thanks. I merged this and fixed the standards issues

**Pull request merged**
