### PR TITLE
Greatday1

### PR DESCRIPTION
**Pull request by soni-111**
program to find the greater of three numbers in php

Before submitting your pull request, check whether your code adheres to PHPMailer
coding standards by running the following command:

`./vendor/bin/php-cs-fixer --diff --dry-run --verbose fix `

And committing eventual changes. It's important that this command uses the specific version of php-cs-fixer configured for PHPMailer, so run `composer install` within the PHPMailer folder to use the exact version it needs.

### CODE REVIEW

**Comment by Sweepr** [comment]
@synchro https://discourse.itk.org/t/github-bot-to-automatically-close-stale-issues-and-pull-requests-that-tend-to-accumulate-during-a-project/1592

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NiklasBr** [comment]
@Sweepr I don't think these are stale, they look like spammy PRs from https://github.com/digitalocean/hacktoberfest/

It appear that also marking them as *invalid* helps not rewarding these unhelpful "contributions".

**Comment by Sweepr** [comment]
@NiklasBr True, but i think stalebot can be handy by not 
giving them attention you can mark them as spam when no other comment's are made.

They won't be marked stale right away.

```
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: spam
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as spam because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

Just an idea to save the hassle/ waste of time and just ignore them.

**Comment by Sweepr** [comment]
@NiklasBr @Synchro 

Some final additional information : https://hacktoberfest.digitalocean.com/hacktoberfest-update

Qoute from the website: 

> In past years, we tried labelling issues “invalid” and “spam” to deter participants from spamming repositories. Unfortunately this has not made as much impact as we had hoped. Therefore, we’re adding new ways to discourage participants from spamming.

**Comment by NiklasBr** [comment]
I read that article just a few days ago, appears they added that section recently.

**Comment by soni-111** [comment]
Yes sir

**Pull request closed without merging**
