### PR TITLE
Tibbel patch 2 alt body

### PR DESCRIPTION
**Pull request by Tibbel**
Before submitting your pull request, be sure your code adheres to PHPMailer
coding standards by running the following command:

`./vendor/bin/php-cs-fixer fix`

And committing eventual changes.

### CODE REVIEW

**Comment by Tibbel** [comment]
okay at this point `'' === $this->AltBody` can be replaced with `$this->alternativeExists()`
But the hole thing is that the AltBody is overwritten every time in the old code
and this case is such a stupid one, where `html2text(Body)` returns an empty string, it can be reached by setting Body only to Characters which will be replaced by `trim`.

**Comment by Synchro** [comment]
But this is in `msgHTML`, which is specifically intended to set both `Body` and `AltBody` in one go, and you've got it doing an HTML to text conversion on something that should be plain text anyway? If you don't want AltBody overwritten, don't call `msgHTML`; just set `AltBody` explicitly. Can you explain the circumstances you're trying to address?

**Comment by Tibbel** [comment]
okay, i think the problem is my script sets first `AltBody` and then calls `msgHTML`.
But from my point of view it's better to ignore the order of settings.

**Comment by Synchro** [comment]
`msgHTML` is a convenience function that explicitly says it's going to overwrite both bodies. Applying `html2text` to an existing plain-text body is likely to cause damage - for example in my own apps I often wrap URLs in `<>` in plain-text bodies (because some clients treat them specially if you do that), and the `strip_tags` in `html2text` would destroy them. If you don't want the body-setting behaviour, don't call it, or set `AltBody` afterwards - which is also what the docs say.

**Pull request closed without merging**
