### PR TITLE
XOAuth Provider - Google,Yahoo,Microsoft

### PR DESCRIPTION
**Pull request by hayageek**
I have added XOAuth Provider support for Google(existing),Yahoo,Microsoft
Check the build status here: https://travis-ci.org/hayageek/PHPMailer/builds/81753588

Locally I have checked the test cases.
$ ../vendor/bin/phpunit --configuration ../travis.phpunit.xml.dist phpmailerXOAuthTest.php 
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

...

Time: 67 ms, Memory: 5.75Mb

OK (3 tests, 15 assertions)

### CODE REVIEW

**Comment by hayageek** [comment]
I did not update composer.json. :(

**Comment by Synchro** [comment]
Nice work, thanks. For future expansion, and ease of adding new providers, I think it would be better to create an abstract base class and then implement each provider as a subclass containing the implementation specific parts, rather than rolling them all into one. It would also mean we don't need the additional `oauthProviderName` property. It would be good if we could retain backward compatibility with the existing google implementation.

A smaller thing is that the 'require's for the class are not necessary - add the paths to the composer.json classmap and the autoloader will find them.

Why did you close this PR?

**Comment by hayageek** [comment]
I did not check in the composer.json.  And i am seing some errors in travis job. But I have tested locally working fine. tested all authentication.
Anyways I requested one more. You can take the changes. make customization. 

https://github.com/PHPMailer/PHPMailer/pull/507

**Comment by Synchro** [comment]
You don't need to do that to make changes to a PR - just push more commits and they will be added automatically. It's considered good practice to squash commits (and force-push) to keep history clean.

**Pull request closed without merging**
