### PR TITLE
ability to create custom message IDs and boundaries

### PR DESCRIPTION
**Pull request by 1stborn**
Due to a problem with Yandex FBL, single possible way to determine sender is a boundary, but there is no way to set it from outside, cuz even i'll do this ( by extending), it will be rewritten by createBody anyway. So I want to propose simple way to customize message boundary and message-id as bonus

### CODE REVIEW

**Comment by Synchro** [comment]
I'll accept this anyway, as it does make it easier to override. What is it that the FBL does? Can't you use VERP? If it breaks return paths, it can't be much use for email!

**Comment by 1stborn** [comment]
FeedBack Lists, Yandex hide all possible way to detect which our user is complain for spam from us and automatically unsubscribe it from mailing lists - they call it "security". But they left some headers of out message untouched `content-type` one of them

**Comment by Synchro** [comment]
Ah, ok, tricky! Yahoo and Hotmail leave everything open.

**Comment by Synchro** [comment]
How can they automatically unsubscribe an address you've sent to without you knowing about it?

**Comment by 1stborn** [comment]
I ask myself the same question :)

**Comment by Synchro** [comment]
Thanks

**Pull request merged**
