### PR TITLE
Revert "Fix PHP <5.4 compatibility"

### PR DESCRIPTION
**Pull request by Synchro**
Reverts PHPMailer/PHPMailer#565

### CODE REVIEW

**Comment by Rikk** [comment]
empty commit?

**Comment by Synchro** [comment]
Not sure what's happened, but things are back to where they were before the incorrect pull so I'm not too worried.

**Comment by Synchro** [comment]
One problem was that I deleted the temp branch immediately after I accepted the reversion PR, which cause the travis build to fail.

**Comment by Rikk** [comment]
Whatever, https://github.com/PHPMailer/PHPMailer/commit/6d7f16a9c930387c9ed419e9c8c3b2fbec7d1706 shows no change to files, for me it looks like you rewrote commits history by overwritting https://github.com/PHPMailer/PHPMailer/commit/d4ca09df492e0df6980769ac63cb7c6b1e994dea. Wasn't it a good fix for compatibility sake?

**Comment by Rikk** [comment]
oops forgot to read a comment in the pr

**Comment by Rikk** [comment]
Whatever, 6d7f16a shows no change to files, for me it looks like you rewrote commits history by overwritting d4ca09d. You could just have changed heads to previous commit (37d355070657a52acaced277de977cb498c31b63)...

**Comment by Synchro** [comment]
No - the entire XOAuth2 implementation requires PHP 5.4, so there is no need for any of the parts involved with it to retain any BC. If anything it's better to fail earlier to avoid people thinking it should work.

**Comment by Synchro** [comment]
Yes, I did make a mess of the reversion - now I know how to do it right next time!

**Pull request merged**
