### PR TITLE
ical method header

### PR DESCRIPTION
**Pull request by Paktusin**
Before submitting your pull request, check whether your code adheres to PHPMailer
coding standards by running the following command:

`./vendor/bin/php-cs-fixer --diff --dry-run --verbose fix `

And committing eventual changes. It's important that this command uses the specific version of php-cs-fixer configured for PHPMailer, so run `composer install` within the PHPMailer folder to use the exact version it needs.

### CODE REVIEW

**Comment by Synchro** [comment]
Not a bad idea - do you find that the iCal support in Outlook works at all?

It would be good to validate it so we can avoid header injection attacks - enforce that it is exactly one of `REQUEST` or `CANCEL` (and whichever other values are valid) before using it.

Also - please fix coding standards (see Travis output) and add test coverage please!

**Comment by Paktusin** [comment]
I tested on Outlook. When Event must cancel and header method and ical file method are different, Outlook do not deleting event from calendar. If methods in header and in body the same (CANCEL) all work properly

**Comment by Paktusin** [comment]
Yes. Its good Idea. I recode solution accroding  this rules:
https://tools.ietf.org/html/rfc5545#section-3.8.4.7

>      The "method" parameter is used to convey the iCalendar objec
>       method or transaction semantics for the calendaring and scheduling
>       information.  It also is an identifier for the restricted set of
>       properties and values of which the iCalendar object consists.  The
>       parameter is to be used as a guide for applications interpreting
>       the information contained within the body part.  It SHOULD NOT be
>       used to exclude or require particular pieces of information unless
>       the identified method definition specifically calls for this
>       behavior.  Unless specifically forbidden by a particular method
>       definition, a text/calendar content type can contain any set of
>       properties permitted by the Calendaring and Scheduling Core Object
>       Specification.  The "method" parameter MUST be specified and MUST
>       be set to the same value as the "METHOD" component property of the
>       iCalendar objects of the iCalendar stream if and only if the
>       iCalendar objects in the iCalendar stream all have a "METHOD"
>       component property set to the same value.

**Comment by Synchro** [comment]
Why did you close this?

**Comment by Paktusin** [comment]
Sorry I'm busy right now

**Pull request closed without merging**
