### PR TITLE
Add an AJAX/Javascript example #1484

### PR DESCRIPTION
**Pull request by udhaykumarbala**
Before submitting your pull request, check whether your code adheres to PHPMailer
coding standards by running the following command:

`./vendor/bin/php-cs-fixer --diff --dry-run --verbose fix `

And committing eventual changes. It's important that this command uses the specific version of php-cs-fixer configured for PHPMailer, so run `composer install` within the PHPMailer folder to use the exact version it needs.

### CODE REVIEW

**Comment by Synchro** [comment]
Thanks for the PR. The JS side of this is fine, but the PHP side could probably use one of the existing examples since it's essentially the same. The only other thing I'd note is that there is no error response handling since the PHP script doesn't return anything particular to an ajax request, so you're left with parsing the text of the response rather than, for example, returning a 400 code along with a status message in JSON.

**Comment by shikkaba** [comment]
Is this going to be added to the main branch ever? Searching to find the example is a slight inconvenience. Slight. Very slight.

**Comment by Synchro** [comment]
@shikkaba You could always have a go at fixing the PR to address the issues I raised on it. I don't want to merge code that doesn't set a good example, which is after all the entire point of these examples!

**Comment by shikkaba** [comment]
@Synchro Maybe! That's a good idea. I'll see what I can do. 👍

**Comment by Synchro** [comment]
I know I said before that the JS in this was OK, but I'd really prefer to see an example without jQuery, i.e. using fetch.

**Comment by Synchro** [comment]
Closed in favour of another PR which provided a good implementation, see https://github.com/PHPMailer/PHPMailer/blob/master/examples/contactform-ajax.phps

**Pull request closed without merging**
