### PR TITLE
composer: indicate ctype ext being used

### PR DESCRIPTION
**Pull request by glensc**
833c35fe3 added ctype extension requirement

### CODE REVIEW

**Comment by glensc** [comment]
also, [ctype_alnum](http://php.net/ctype_alnum) is locale aware, are you sure that is intended?

**Comment by glensc** [comment]
sadly i don't see testcases being submitted. it would be easy to rewrite it with regexp knowing it behaves the same as before with given testcases. it's hard figuring out what the method is supposed to do now :)

**Comment by glensc** [comment]
it's supposed to handle some kind of escaping for windows that php native escapeshellarg/escapeshellcmd don't do? i've came across this library at some point in the past: https://github.com/johnstevenson/winbox-args

**Comment by Synchro** [comment]
This function tests to see if the passed string is likely to need any escaping at all, firstly by using the built-in functions, but if they pass, by allowing only a very restricted set of characters, which amount to not much more than `[a-zA-Z0-9@\._-]` - note that this does not include `=+'"\` because they are used in paths, separators and escaping in various different shells. The reasoning for this is that [the PHP shell escape functions are not reliable](https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36), so we need to simply avoid the need to do any escaping at all, if possible.

**Comment by Synchro** [comment]
And tests would indeed be welcome too.

**Comment by glensc** [comment]
#938 - no actual tests filled

**Pull request merged**
