### PR TITLE
Added Sinhala to Language Folder

### PR DESCRIPTION
**Pull request by Senasum**
Added Sinhala to Language Folder

### CODE REVIEW

**Comment by Synchro** [comment]
Thanks

**Comment by Senasum** [comment]
Hay Synchro I am willing to contribute more to this project. I'm a student  of Middlesex university UK and I have one subject that I need to contribute for one of the Open source projects.

**Comment by Synchro** [comment]
Take a look through the open tickets and see if there's anything you can help with, even if it's only documentation. You could also look at the unit tests and see what you can do to improve coverage.

**Comment by Senasum** [comment]
okay I am working hard on it

**Comment by Synchro** [comment]
Something appears to have gone very wrong with this translation. Please could you fix and resubmit it? Otherwise I will need to delete it.

**Pull request merged**
