### PR TITLE
Minor correction of attribute description

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Corrected the description of Parameters to `$action_function` which otherwise gave me a lot of trouble. The corrected params are passed in `doCallback()` as arrays but here it was mentioned as strings.

### CODE REVIEW

**Comment by Synchro** [comment]
Thanks

**Comment by Synchro** [comment]
Incidentally I'd be interested in hearing how you're using these callbacks - it's something I'm considering removing from PHPMailer, or at least revising heavily as the current implementation is pretty bad! A simple function injection would be much better that what is here now, but I don't know that it's actually very useful at all anyway.

**Comment by manzoorwanijk** [comment]
I'm using it as a trigger to process the sent emails in one of my WordPress plugins.

**Comment by Synchro** [comment]
Since you know the addresses you're feeding in, could you not achieve the same thing by checking the return status from `send()`?

**Comment by manzoorwanijk** [comment]
Emails are not sent by my plugin, rather they are sent by other plugins or by WordPress itself. So, I needed a hook by which I could monitor the sent email. I could not find anything better than this.

**Pull request merged**
