### PR TITLE
Add an option to get the send error in array format

### PR DESCRIPTION
**Pull request by christiandavilakoobin**

### CODE REVIEW

**Comment by christiandavilakoobin** [comment]
I'm not sure if this is the best approach, but I need to get the error code returned by the smtp server to control it manually, e.g., to control the AWS SES limits (https://docs.aws.amazon.com/ses/latest/DeveloperGuide/troubleshoot-smtp.html) . If you reach the limit, they return a 454 error code. If all the error is concatenated in the ErrorInfo var, is more difficult to control it.

**Comment by Synchro** [comment]
I think this is the same thing that was requested in #1579 some time ago.

**Comment by christiandavilakoobin** [comment]
Yes, you're right. I can change the $STMPerror varname to ErrorCode to fit your suggestion, if you prefer it.

**Comment by Synchro** [comment]
Can you show examples of what you're getting in `ErrorCode` and why you think an array is appropriate / needed? From its name I would expect `ErrorCode` to contain an error code, not an array!

**Comment by christiandavilakoobin** [comment]
I changed it to `ErrorDetails`. I need it because with the SES daily and by second limits, I have to control it to retry sending emails later.

Here is an example:

```
try
{
    $mail->send();
}
catch (Exception $e)
{
   // If a limit is reached, AWS SES retruns a 454 error code
   if ($mail->ErrorDetail['code'] == 454)
   {
      // According AWS docs, we have the following error description.
      if ($mail->ErrorDetail['detail'] == 'Throttling failure: Maximum sending rate exceeded')
      {
         // Retry in a few seconds
      }
      elseif ($mail->ErrorDetail['detail'] == 'Throttling failure: Daily message quota exceeded')
      {
         // Wait until tomorrow
      }
      else
      {
         // Unkown SES issue
      }
   }
}
```

**Pull request closed without merging**
