### PR TITLE
grammar

### PR DESCRIPTION
**Pull request by aranaur**

### CODE REVIEW

**Comment by Synchro** [comment]
I agree that this could be phrased better, but this isn't much of an improvement!

**Comment by aranaur** [comment]
I agree. How about "Alternatively, you may copy the contents of the PHPMailer folder into the `include_path` directory specified in your PHP configuration."?

**Comment by Synchro** [comment]
I'd go for plural, shorten it a bit:
 > Alternatively, copy the contents of the PHPMailer folder into one of the `include_path` directories specified in your PHP configuration.

**Comment by aranaur** [comment]
That sounds a lot better.

**Comment by Synchro** [comment]
If you want to tweak your PR with that, I'll accept it, since you got this ball rolling.

**Comment by aranaur** [comment]
Updated, thanks.

**Pull request merged**
