### PR TITLE
Tests: move line length detection tests to own file

### PR DESCRIPTION
**Pull request by jrfnl**
This is a next PR in a series of PRs to improve the test suite and make it easier to maintain.
The principle of these changes was proposed to and discussed with the maintainer prior to work being started on it.

I'm splitting this up into several PRs to 1) allow for easier review and 2) allow the repo to benefit from the changes as quickly as possible. (the complete series is still a WIP).

Previous PRs in this series: #2372, #2376, #2377, #2378, #2379, #2380, #2381, #2382, #2383, #2384

### HasLineLongerThanMaxTest: various test tweaks

Minor test tweaks:
* Add `@covers` tag.
* Inline comment punctuation.
* Minor code readability tweaks.

### CODE REVIEW

**Comment by Synchro** [comment]
Just FYI, all the comments without punctuation are that way because there was a previous coding standard that required *only* that the main description line in a docblock ended with punctuation, and didn't allow it anywhere else. Peculiar, but I was going with the flow...

**Comment by jrfnl** [comment]
> Just FYI, all the comments without punctuation are that way because there was a previous coding standard that required only that the main description line in a docblock ended with punctuation, and didn't allow it anywhere else. Peculiar, but I was going with the flow...

Understood. You're okay with me fixing them up though ?

**Comment by Synchro** [comment]
Sure!

**Comment by jrfnl** [comment]
@Synchro As I think I mentioned before, I'd be happy to add a set of comment/docblock related sniffs to the CS ruleset at some point in the future, if you like. For now, I'll just fix up whatever I come across when touching the code anyway.

**Comment by Synchro** [comment]
It's all good – I'm trying not to interrupt you while you're working wonders!

**Pull request merged**
