### PR TITLE
[Fixes #1847] Building docs with GitHub Actions

### LINKED ISSUE #1847: Configure auto-generation of API docs
[The API documentation](http://phpmailer.github.io/PHPMailer/) is generated from embedded [phpdoc](https://phpdoc.org) comments in the source code. This is occasionally manually updated (by running `phpdoc` in the project folder, configured via the [`phpdoc.dist.xml`](https://github.com/PHPMailer/PHPMailer/blob/master/phpdoc.dist.xml) file) and pushed to the [gh-pages branch](https://github.com/PHPMailer/PHPMailer/tree/gh-pages).

It would be much better if this process was automated via a git hook, github actions, or whatever works best, so I'm looking for help in configuring that.

### PR DESCRIPTION
**Pull request by freezy-sk**
Building docs with GitHub Actions.
Requires setting [Personal Access Token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) with `repo` permissions as `GH_PAT` secret of this repository

### CODE REVIEW

**Comment by freezy-sk** [comment]
@Synchro sorry I forget to change workflow file `.github/workflows/docs.yaml` to run only for master branch.
could you please change 
```
on: push
```
to
```
on:
  push:
    branches:
      - master
```

thank you

**Comment by Synchro** [comment]
Thanks, I've done that. I created a PAT with `repo` privs called `GH_PAT` and enabled Github actions, but I'm not seeing anything. Is there something else I need to do?

**Comment by freezy-sk** [comment]
if you are signed up for Actions beta (https://github.com/features/actions), try enabling also third party actions in settings
image
also ensure you have added your PAT to this repository secrets as GH_PAT
image

**Comment by Synchro** [comment]
Ah, I needed to add actions to the org, not my own account. Actions are now showing up, but hasn't done anything - might need a push to trigger it.

**Comment by Synchro** [comment]
OK, I did a push, which triggered the action correctly, but [it failed](https://github.com/PHPMailer/PHPMailer/runs/244604323) due to a permissions problem within the build system. Any idea how to fix that?

One other thought - shouldn't the publish stage depend upon the success of the build stage?

**Comment by freezy-sk** [comment]
good point. it should depend on the build stage. or it can be done in one job without uploading artifacts between jobs

**Pull request merged**
